# Build and run tests on push to any branch except master

name: Branch CI

on:
  push:
    branches:
      - '**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Initialize Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:parallel
